### ISSUE TITLE
A code I would like to upstream

### ISSUE THREAD

**Issue by JanisErdmanis** [fcasal/CryptoUtils.jl#1]
Hello! 

The package seems to fit the goal for providing some frequently used routines from number theory to make our cryptographic algorithms. Currently, I have implemented the digital signature algorithm in Julia, which sits in CryptoSignatures.jl as well as cryptographic groups CryptoGroups.jl, and now I am working on Diffie-Hellman key exchange. During the development, I have wrapped two undocumented routines for random integer and random prime generation from Paillier.jl. Also, I have written some code for modular inverse, which seems could belong to this package. 

Thus would you accept a pull request
+ Which takes code from https://github.com/hardbyte/Paillier.jl/blob/master/src/utilities.jl for integer and prime generation with a fixed size
+  Modular inverse functions which are currently sitting here - https://github.com/PeaceFounder/CryptoSignatures.jl/blob/master/src/dsasignatures.jl

**Comment by fcasal** [comment]
Hi there, for some reason github did not notify me of your issue.

- what is the advantage of those prime number generation functions vs the provided random_prime?

- why not use Julia's invmod instead of implementing this one in DSA?

**Comment by JanisErdmanis** [comment]
Thanks. I did not know that `invmod` stands for a modular inverse for Julia. It seems that there is no benefit to keeping using my implementation and I could make my code shorter :) 

Also, I overlooked the `random_prime` function at this library. It is what I need. So I close the issue because I have no code to upstream.
